name: Pull Request

on:
  workflow_call:
    secrets:
       CHARMHUB_TOKEN:
         required: true
jobs:
  lib-check:
    name: Check libraries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Check libs
        uses: canonical/charming-actions/check-libraries@2.0.0-rc2
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
  static-analysis:
    name: Static Analysis
    uses: canonical/observability/.github/workflows/_static-analysis.yaml@main
  linting:
    name: Linting
    uses: canonical/observability/.github/workflows/_linting.yaml@main
  unit-test:
    name: Unit Tests
    uses: canonical/observability/.github/workflows/_unit-tests.yaml@main
  integration-test:
    name: Integration Tests
    uses: canonical/observability/.github/workflows/_integration-tests.yaml@main
