# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

# Usage documentation: static-code-analysis.md

name: Tiobe TiCS Analysis

on:
  workflow_call:

jobs:
  scan:
    name: Scan and upload
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout the project
        uses: actions/checkout@v4
        with:
          repository: canonical/${{ github.event.repository.name }}

      - name: Install dependencies
        run: |
          sudo snap install charmcraft --classic
          sudo apt update && sudo apt install -y pipx
          sudo apt install -y python3-flake8 pylint
          pipx install coverage
          pipx install "coverage[toml]"
          pipx install tox

      - name: Run tox tests to create coverage.xml
        run: |
          tox -e unit && coverage xml

      - name: Move results to necessary folder for TICS
        run: |
          mkdir -p ./cover
          mv ./coverage.xml ./cover/
          source .tox/unit/bin/activate

      - name: Run TICS analysis with github-action
        uses: tiobe/tics-github-action@v3
        env:
          PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/.tox/unit
        with:
          mode: qserver
          project: ${{ github.event.repository.name }}
          branchdir: .
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true
