name: Release Charm

on:
  workflow_call:
    secrets:
      CHARMHUB_TOKEN:
        required: true

jobs:
  quality-checks:
    uses: canonical/observability/.github/workflows/_quality-checks.yaml@main
    secrets: inherit
  release-charm:
    uses: canonical/observability/.github/workflows/_release_charm.yaml@main
    secrets: inherit
